### ISSUE TITLE
Offline Mode?

### ISSUE THREAD

**Issue by MysticAx0lotl** [Vanilagy/MarbleBlast#11]
First off, I'd like to say that I _love_ what you've done here. It's nice to see one of my favorite games of all time finally accessible to more platforms than just Windows and Mac. I also _adore_ how there is an option to play it in mobile. I have a suggestion on how to improve the mobile experience. Since this is a Progressive Web App, there is an option to install it as an Android/iOS application. However, doing so only creates a shortcut, it doesn't actually download much. This means you have to stay connected to the internet to play the game, which I find somewhat annoying. I did some research and found that a PWA has the ability to cache its files to the device it's installed on, making it useable offline. Would it be feasible to implement this feature here?

**Comment by Vanilagy** [comment]
I'm glad you enjoy the site!

Regarding offline mode: Yes, it's definitely planned. The PWA features I threw in when I released mobile support were just the bare minimum to get it to install on the home screen, while technically still being just an alias for the website and requiring internet. I definitely want to add offline mode someday, but implementing it is not trivial: What data gets downloaded, exactly? Sure, I can download the JS and the UI images and whatever, but what about the levels? All levels in total are about 4 GB, so that's not feasible. The best I've come up with so far is manually marking levels as "I want this to be available offline", like it works in Spotify.

**Comment by Techguy791** [comment]
That sounds great! I wonder if compression would also be an option, like storing everything in a tarball. That could save storage, with the only cost of slightly longer loading times.

**Comment by Vanilagy** [comment]
Yeah, I've thought about it, but still is already quite compressed. Everything the server sends over is gzipped - I don't think wrapping stuff up would yield much benefit, maybe in the way that it saves on request count - but makes the system more complex. Gotta see!
